AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/IndentationWidth:
  AllowedPatterns: ['^\s*module']

Layout/LineLength:
  Max: 120
